return {
	Title = "太吾村建筑增强",
	Author = "WhiteMind",
	Description = "允许提升大部分建筑的等级上限\n\n太吾村作为太吾传人的后勤中心，怎能如此孱弱？必须狠狠的加强！\n\n注：\n修炼突破类建筑不建议将等级上限调至 20 级以上，因为每级 -5% 历练消耗，21 级直接电表倒转。",
	Cover = "Cover.png",
	WorkshopCover = "Cover.png",
	Version = "0.1.0.0",
	GameVersion = "0.0.72.14",
	Source = 0,
	Visibility = 0,
	ChangeConfig = true,
	HasArchive = false,
	NeedRestartWhenSettingChanged = true,
	UpdateLogList = {
		[1] = {
			Timestamp = 1722858013,
		},
	},
	FrontendPlugins = {
		[1] = "BuildingEnhancementFrontendPlugin.dll",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Slider",
			Key = "Slider_TaiwuVillageMaxLevel",
			DisplayName = "太吾村等级上限",
			Description = "提升太吾村等级上限到该数值。",
			MinValue = 20,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 99,
		},
		[2] = {
			SettingType = "Slider",
			Key = "Slider_ResidenceMaxLevel",
			DisplayName = "居所等级上限",
			Description = "提升居所等级上限到该数值。",
			MinValue = 20,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 99,
		},
		[3] = {
			SettingType = "Slider",
			Key = "Slider_ComfortableHouseMaxLevel",
			DisplayName = "厢房等级上限",
			Description = "提升厢房等级上限到该数值。",
			MinValue = 5,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 10,
		},
		[4] = {
			SettingType = "Slider",
			Key = "Slider_WarehouseMaxLevel",
			DisplayName = "仓库等级上限",
			Description = "提升仓库等级上限到该数值。",
			MinValue = 20,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 99,
		},
		[5] = {
			SettingType = "Slider",
			Key = "Slider_ResourceMaxLevel",
			DisplayName = "资源类建筑等级上限",
			Description = "提升资源类建筑等级上限到该数值。\n资源类建筑包括天然资源、可收获资源建筑、可收获物品建筑。",
			MinValue = 20,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 40,
		},
		[6] = {
			SettingType = "Slider",
			Key = "Slider_ReadingMaxLevel",
			DisplayName = "研读效率类建筑等级上限",
			Description = "提升研读效率类建筑等级上限到该数值。\n研读效率类建筑，即功法、技艺的基础建筑，包括练功房、琴舍、弈轩等。",
			MinValue = 20,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 40,
		},
		[7] = {
			SettingType = "Slider",
			Key = "Slider_FlashMaxLevel",
			DisplayName = "灵光乍现类建筑等级上限",
			Description = "提升灵光乍现类建筑等级上限到该数值。\n如移情居、琉璃馆、龙龟山等。",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 40,
		},
		[8] = {
			SettingType = "Slider",
			Key = "Slider_KungfuMaxLevel",
			DisplayName = "修炼突破类建筑等级上限",
			Description = "提升修炼突破类建筑等级上限到该数值。\n如静室、隔世塔等。\n每级 -5% 历练消耗 / +3% 突破成功率，所以等级不宜过高，超过 20 级历练就电表倒转了。",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 15,
		},
		[9] = {
			SettingType = "Slider",
			Key = "Slider_AttainmentMaxLevel",
			DisplayName = "造诣类建筑等级上限",
			Description = "提升造诣类建筑等级上限到该数值。\n如木料标本、神木林等。\n每级 +10 造诣 / -5 造诣需求。",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 15,
		},
		[10] = {
			SettingType = "Slider",
			Key = "Slider_MoneyMaxLevel",
			DisplayName = "银钱类建筑等级上限",
			Description = "提升银钱类建筑等级上限到该数值。\n如镖局、铁匠铺、赌坊等。\n每级加产能，过高的产能会导致铁匠铺等建筑售卖出天价，所以等级不宜过高。",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 20,
		},
		[11] = {
			SettingType = "Slider",
			Key = "Slider_AuthorityMaxLevel",
			DisplayName = "威望类建筑等级上限",
			Description = "提升威望类建筑等级上限到该数值。\n知客亭、金铺、游园等。\n每级加产能，过高的产能会导致金铺等建筑售卖出天价，所以等级不宜过高。",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 20,
		},
		[12] = {
			SettingType = "Slider",
			Key = "Slider_GetVillagerMaxLevel",
			DisplayName = "招募类建筑等级上限",
			Description = "提升招募类建筑等级上限到该数值。\n如炼神峰、知音阁、贤士馆等",
			MinValue = 10,
			MaxValue = 99,
			StepSize = 1,
			DefaultValue = 40,
		},
	},
	FileId = 3302686229,
	TagList = {
		[1] = "Modifications",
		[2] = "Compatible Mods",
	},
	DetailImageList = {
		[1] = "workshop1.jpg",
		[2] = "workshop2.jpg",
		[3] = "workshop3.jpg",
		[4] = "workshop4.jpg",
	},
}
